#!/usr/bin/env python3
"""Generate a yazi flavor from the active Ghostty theme.

Reads the resolved Ghostty config (`ghostty +show-config`, which already has
the active theme's palette applied — works for built-in themes, custom themes
in ~/.config/ghostty/themes, and includes/overrides) and writes:

    ~/.config/yazi/flavors/ghostty.yazi/flavor.toml   UI colors
    ~/.config/yazi/flavors/ghostty.yazi/tmtheme.xml   code-preview highlighting

Why this exists: yazi's default theme follows the terminal's ANSI palette, but
two things don't — the syntect code-preview theme (hardcoded default) and the
reverse-video hover indicators, which turn whole rows into blocks of whatever
neon a theme puts in its blue slot. This maps the actual theme hexes onto
those spots deliberately.

Stdlib only. Restart yazi after running to pick up changes.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import uuid
from string import Template

__version__ = "0.1.0"

MACOS_APP_BIN = "/Applications/Ghostty.app/Contents/MacOS/ghostty"
DEFAULT_OUT = "~/.config/yazi/flavors/ghostty.yazi"


def find_ghostty(explicit=None):
    if explicit:
        if os.path.exists(explicit) or shutil.which(explicit):
            return explicit
        sys.exit(f"ghostty-yazi-flavor: ghostty binary not found at {explicit!r}")
    found = shutil.which("ghostty")
    if found:
        return found
    if os.path.exists(MACOS_APP_BIN):
        return MACOS_APP_BIN
    sys.exit(
        "ghostty-yazi-flavor: ghostty binary not found on PATH "
        f"or at {MACOS_APP_BIN}; pass --ghostty <path>."
    )


def resolved_config(ghostty):
    out = subprocess.run(
        [ghostty, "+show-config"], capture_output=True, text=True, check=True
    ).stdout
    return out.splitlines()


def norm_hex(value):
    value = value.strip()
    if not value:
        return None
    if re.fullmatch(r"#?[0-9a-fA-F]{6}", value):
        return "#" + value.lstrip("#").lower()
    return None


def parse(lines):
    palette, scalars = {}, {}
    for line in lines:
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key, value = key.strip(), value.strip()
        if key == "palette":
            m = re.fullmatch(r"(\d+)\s*=\s*(#?[0-9a-fA-F]{6})", value)
            if m and int(m.group(1)) < 16:
                palette[int(m.group(1))] = norm_hex(m.group(2))
        elif key in (
            "background",
            "foreground",
            "cursor-color",
            "selection-background",
            "selection-foreground",
            "theme",
        ):
            scalars[key] = value
    return palette, scalars


def render_flavor(theme_name, p, bg, fg):
    v = {
        "theme": theme_name,
        "bg": bg, "fg": fg,
        **{f"p{i}": p[i] for i in range(16)},
    }
    return Template("""\
#:schema https://yazi-rs.github.io/schemas/theme.json
# GENERATED by ghostty-yazi-flavor from Ghostty theme "$theme" — do not edit.
# Partial on purpose: yazi merges this over its preset, and the preset's named
# ANSI colors already follow the terminal palette. Only the spots that don't
# follow it (or follow it badly) are overridden here.

[mgr]
cwd = { fg = "$p6" }
border_style = { fg = "$p8" }
find_keyword = { fg = "$p3", bold = true, underline = true }
find_position = { fg = "$p5", bg = "reset", bold = true }

# Default is reverse-video, which turns the hovered row into a solid block of
# its own text color. A neutral bright-black bar reads as "cursor" instead.
[indicator]
parent = { bg = "$p8", bold = true }
current = { bg = "$p8", bold = true }
preview = { underline = true }

[tabs]
active = { fg = "$bg", bg = "$p4", bold = true }
inactive = { fg = "$p8" }

[mode]
normal_main = { fg = "$bg", bg = "$p4", bold = true }
normal_alt = { fg = "$p4", bg = "$p8" }
select_main = { fg = "$bg", bg = "$p3", bold = true }
select_alt = { fg = "$p3", bg = "$p8" }
unset_main = { fg = "$bg", bg = "$p1", bold = true }
unset_alt = { fg = "$p1", bg = "$p8" }
""").substitute(v)


def render_tmtheme(theme_name, p, bg, fg, cursor, selbg):
    def scope(name, scopes, color=None, style=None, background=None):
        settings = ""
        if color:
            settings += f"\n\t\t\t\t<key>foreground</key><string>{color}</string>"
        if background:
            settings += f"\n\t\t\t\t<key>background</key><string>{background}</string>"
        if style is not None:
            settings += f"\n\t\t\t\t<key>fontStyle</key><string>{style}</string>"
        return f"""\t\t<dict>
\t\t\t<key>name</key><string>{name}</string>
\t\t\t<key>scope</key><string>{scopes}</string>
\t\t\t<key>settings</key>
\t\t\t<dict>{settings}
\t\t\t</dict>
\t\t</dict>"""

    scopes = "\n".join([
        scope("Comment", "comment, punctuation.definition.comment", p[8], "italic"),
        scope("String", "string", p[2]),
        scope("Number", "constant.numeric", p[3]),
        scope("Constant", "constant.language, constant.character", p[5]),
        scope("Keyword", "keyword, storage.modifier", p[5]),
        scope("Storage", "storage.type", p[4]),
        scope("Function", "entity.name.function, support.function", p[4]),
        scope("Type", "entity.name.type, entity.name.class, support.type, support.class", p[3]),
        scope("Tag", "entity.name.tag", p[1]),
        scope("Attribute", "entity.other.attribute-name", p[3]),
        scope("Object key", "support.type.property-name, meta.object-literal.key", p[6]),
        scope("Variable", "variable", fg),
        scope("Invalid", "invalid", bg, None, p[1]),
        scope("Inserted", "markup.inserted", p[2]),
        scope("Deleted", "markup.deleted", p[1]),
        scope("Heading", "markup.heading", p[4], "bold"),
        scope("Bold", "markup.bold", None, "bold"),
        scope("Italic", "markup.italic", None, "italic"),
        scope("Raw", "markup.raw", p[2]),
        scope("Link", "markup.underline.link", p[6], "underline"),
    ])

    tm_uuid = str(uuid.uuid5(uuid.NAMESPACE_DNS, f"ghostty-yazi/{theme_name}")).upper()
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- GENERATED by ghostty-yazi-flavor from Ghostty theme "{theme_name}" - do not edit. -->
<plist version="1.0">
<dict>
\t<key>name</key><string>Ghostty {theme_name}</string>
\t<key>uuid</key><string>{tm_uuid}</string>
\t<key>settings</key>
\t<array>
\t\t<dict>
\t\t\t<key>settings</key>
\t\t\t<dict>
\t\t\t\t<key>background</key><string>{bg}</string>
\t\t\t\t<key>foreground</key><string>{fg}</string>
\t\t\t\t<key>caret</key><string>{cursor}</string>
\t\t\t\t<key>selection</key><string>{selbg}</string>
\t\t\t\t<key>lineHighlight</key><string>{selbg}</string>
\t\t\t\t<key>invisibles</key><string>{p[8]}</string>
\t\t\t</dict>
\t\t</dict>
{scopes}
\t</array>
</dict>
</plist>
"""


def main():
    ap = argparse.ArgumentParser(
        prog="ghostty-yazi-flavor",
        description="Generate a yazi flavor from the active Ghostty theme.",
    )
    ap.add_argument("--out", default=DEFAULT_OUT,
                    help=f"output flavor directory (default: {DEFAULT_OUT})")
    ap.add_argument("--ghostty", default=None,
                    help="path to the ghostty binary (default: autodetect)")
    ap.add_argument("--version", action="version", version=__version__)
    args = ap.parse_args()

    ghostty = find_ghostty(args.ghostty)
    palette, scalars = parse(resolved_config(ghostty))
    missing = [i for i in range(16) if i not in palette]
    if missing:
        sys.exit(f"ghostty-yazi-flavor: palette slots missing: {missing}")

    p = palette
    bg = norm_hex(scalars.get("background", "")) or p[0]
    fg = norm_hex(scalars.get("foreground", "")) or p[7]
    cursor = norm_hex(scalars.get("cursor-color", "")) or fg
    selbg = norm_hex(scalars.get("selection-background", "")) or p[8]
    theme_name = scalars.get("theme") or "(no theme set)"

    out_dir = os.path.expanduser(args.out)
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "flavor.toml"), "w") as f:
        f.write(render_flavor(theme_name, p, bg, fg))
    with open(os.path.join(out_dir, "tmtheme.xml"), "w") as f:
        f.write(render_tmtheme(theme_name, p, bg, fg, cursor, selbg))
    print(f'ghostty-yazi-flavor: wrote {out_dir} from theme "{theme_name}"')
    print("restart yazi to pick it up")


if __name__ == "__main__":
    main()
